version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.10
    - 3.3.11
    - 3.3.12
    - 3.3.13
    - 3.3.14
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.21.0
    - 1.21.1
  - dependency-name: "@graphql-codegen/typescript-react-apollo"
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@graphql-codegen/typescript-operations"
    versions:
    - 1.17.14
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
